spring:
  main:
    banner-mode: off
  liquibase:
    enabled: true
    url: mongodb+srv://pamail08:GrdjOzRpRV05hrtV@cluster0.gxwfkmx.mongodb.net/restaurant_service
    change-log: classpath:/db/changelog/changelog-master.xml

bot:
  name: ${bot.name}
  token: ${bot.token}

server:
  port: 8080
